FROM python:slim-bullseye
WORKDIR /usr/src/app
COPY requirements.txt .
RUN pip3 install --no-cache-dir --upgrade -r requirements.txt
COPY ./  ./
CMD ["python", "-m", "uvicorn", "get_activities:app", "--host", "0.0.0.0", "--port", "80"]
