version: "3.8"

services:
  ####################################
  # Service: Alert
  ####################################
  alert:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - 'dev.env'
    ports:
      - "30000:5000"
